name: Docker CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image and Push the image to DockerHUB
        run: docker build -t leo_bot .

      - name: Deploy Docker container
        run: |
          docker stop leo_bot || true
          docker rm leo_bot || true
          docker run --restart unless-stopped --name leo_bot -d leo_bot